name: Check Pull Request
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # Check that only webgpu.yml is affected by the PR
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: test
        run: |
          echo "summary=There was a validation error" >> "$GITHUB_OUTPUT"
          exit 1

      # Report previous step outcome as a GitHub Check for the PR
      - uses: LouisBrunner/checks-action@v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            { "summary":"${{ steps.test.outputs.summary }}" }
