name: Check Pull Request
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # Check that only webgpu.yml is affected by the PR
  check:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/create-outputs@v0.0.0-fake
        id: test
      - uses: LouisBrunner/checks-action@v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            { "summary":"${{ steps.test.outputs.summary }}" }
